version: '3.1'

services:

  db:
    image: mysql
    container_name: mysql
    ports:
    - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: secret
    volumes:
    - /storage/docker/mysql-datadir:/var/lib/mysql
